//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PBN.proxibusnicweb {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProxiBusNicWSSoap", Namespace="http://tempuri.org/")]
    public partial class ProxiBusNicWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AgregarParadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarParadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarSugerenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarBusParadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarBusOperationCompleted;
        
        private System.Threading.SendOrPostCallback CambiarClaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProxiBusNicWS() {
            this.Url = "http://proxibusnicweb.somee.com/ProxiBusNicWeb/ProxiBusNicWS.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AgregarParadaCompletedEventHandler AgregarParadaCompleted;
        
        /// <remarks/>
        public event BuscarParadaCompletedEventHandler BuscarParadaCompleted;
        
        /// <remarks/>
        public event AgregarSugerenciaCompletedEventHandler AgregarSugerenciaCompleted;
        
        /// <remarks/>
        public event AgregarBusParadasCompletedEventHandler AgregarBusParadasCompleted;
        
        /// <remarks/>
        public event AgregarBusCompletedEventHandler AgregarBusCompleted;
        
        /// <remarks/>
        public event CambiarClaveCompletedEventHandler CambiarClaveCompleted;
        
        /// <remarks/>
        public event CrearUsuarioCompletedEventHandler CrearUsuarioCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarParada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AgregarParada(string descripcion, string alias, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] foto, bool estado, string usuario) {
            object[] results = this.Invoke("AgregarParada", new object[] {
                        descripcion,
                        alias,
                        foto,
                        estado,
                        usuario});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarParadaAsync(string descripcion, string alias, byte[] foto, bool estado, string usuario) {
            this.AgregarParadaAsync(descripcion, alias, foto, estado, usuario, null);
        }
        
        /// <remarks/>
        public void AgregarParadaAsync(string descripcion, string alias, byte[] foto, bool estado, string usuario, object userState) {
            if ((this.AgregarParadaOperationCompleted == null)) {
                this.AgregarParadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarParadaOperationCompleted);
            }
            this.InvokeAsync("AgregarParada", new object[] {
                        descripcion,
                        alias,
                        foto,
                        estado,
                        usuario}, this.AgregarParadaOperationCompleted, userState);
        }
        
        private void OnAgregarParadaOperationCompleted(object arg) {
            if ((this.AgregarParadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarParadaCompleted(this, new AgregarParadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarParada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int BuscarParada(string descripcion, string alias, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] foto, bool estado, string usuario) {
            object[] results = this.Invoke("BuscarParada", new object[] {
                        descripcion,
                        alias,
                        foto,
                        estado,
                        usuario});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarParadaAsync(string descripcion, string alias, byte[] foto, bool estado, string usuario) {
            this.BuscarParadaAsync(descripcion, alias, foto, estado, usuario, null);
        }
        
        /// <remarks/>
        public void BuscarParadaAsync(string descripcion, string alias, byte[] foto, bool estado, string usuario, object userState) {
            if ((this.BuscarParadaOperationCompleted == null)) {
                this.BuscarParadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarParadaOperationCompleted);
            }
            this.InvokeAsync("BuscarParada", new object[] {
                        descripcion,
                        alias,
                        foto,
                        estado,
                        usuario}, this.BuscarParadaOperationCompleted, userState);
        }
        
        private void OnBuscarParadaOperationCompleted(object arg) {
            if ((this.BuscarParadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarParadaCompleted(this, new BuscarParadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarSugerencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AgregarSugerencia(string descripcion, string usuario, int idParada) {
            object[] results = this.Invoke("AgregarSugerencia", new object[] {
                        descripcion,
                        usuario,
                        idParada});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarSugerenciaAsync(string descripcion, string usuario, int idParada) {
            this.AgregarSugerenciaAsync(descripcion, usuario, idParada, null);
        }
        
        /// <remarks/>
        public void AgregarSugerenciaAsync(string descripcion, string usuario, int idParada, object userState) {
            if ((this.AgregarSugerenciaOperationCompleted == null)) {
                this.AgregarSugerenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarSugerenciaOperationCompleted);
            }
            this.InvokeAsync("AgregarSugerencia", new object[] {
                        descripcion,
                        usuario,
                        idParada}, this.AgregarSugerenciaOperationCompleted, userState);
        }
        
        private void OnAgregarSugerenciaOperationCompleted(object arg) {
            if ((this.AgregarSugerenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarSugerenciaCompleted(this, new AgregarSugerenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarBusParadas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AgregarBusParadas(int idBus, int idParada) {
            object[] results = this.Invoke("AgregarBusParadas", new object[] {
                        idBus,
                        idParada});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarBusParadasAsync(int idBus, int idParada) {
            this.AgregarBusParadasAsync(idBus, idParada, null);
        }
        
        /// <remarks/>
        public void AgregarBusParadasAsync(int idBus, int idParada, object userState) {
            if ((this.AgregarBusParadasOperationCompleted == null)) {
                this.AgregarBusParadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarBusParadasOperationCompleted);
            }
            this.InvokeAsync("AgregarBusParadas", new object[] {
                        idBus,
                        idParada}, this.AgregarBusParadasOperationCompleted, userState);
        }
        
        private void OnAgregarBusParadasOperationCompleted(object arg) {
            if ((this.AgregarBusParadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarBusParadasCompleted(this, new AgregarBusParadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarBus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AgregarBus(string numRuta, bool estado, string usuario) {
            object[] results = this.Invoke("AgregarBus", new object[] {
                        numRuta,
                        estado,
                        usuario});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarBusAsync(string numRuta, bool estado, string usuario) {
            this.AgregarBusAsync(numRuta, estado, usuario, null);
        }
        
        /// <remarks/>
        public void AgregarBusAsync(string numRuta, bool estado, string usuario, object userState) {
            if ((this.AgregarBusOperationCompleted == null)) {
                this.AgregarBusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarBusOperationCompleted);
            }
            this.InvokeAsync("AgregarBus", new object[] {
                        numRuta,
                        estado,
                        usuario}, this.AgregarBusOperationCompleted, userState);
        }
        
        private void OnAgregarBusOperationCompleted(object arg) {
            if ((this.AgregarBusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarBusCompleted(this, new AgregarBusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CambiarClave", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CambiarClave(string correo, string Pass) {
            object[] results = this.Invoke("CambiarClave", new object[] {
                        correo,
                        Pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CambiarClaveAsync(string correo, string Pass) {
            this.CambiarClaveAsync(correo, Pass, null);
        }
        
        /// <remarks/>
        public void CambiarClaveAsync(string correo, string Pass, object userState) {
            if ((this.CambiarClaveOperationCompleted == null)) {
                this.CambiarClaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCambiarClaveOperationCompleted);
            }
            this.InvokeAsync("CambiarClave", new object[] {
                        correo,
                        Pass}, this.CambiarClaveOperationCompleted, userState);
        }
        
        private void OnCambiarClaveOperationCompleted(object arg) {
            if ((this.CambiarClaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CambiarClaveCompleted(this, new CambiarClaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoSW CrearUsuario(string Email, string Pass) {
            object[] results = this.Invoke("CrearUsuario", new object[] {
                        Email,
                        Pass});
            return ((ResultadoSW)(results[0]));
        }
        
        /// <remarks/>
        public void CrearUsuarioAsync(string Email, string Pass) {
            this.CrearUsuarioAsync(Email, Pass, null);
        }
        
        /// <remarks/>
        public void CrearUsuarioAsync(string Email, string Pass, object userState) {
            if ((this.CrearUsuarioOperationCompleted == null)) {
                this.CrearUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearUsuarioOperationCompleted);
            }
            this.InvokeAsync("CrearUsuario", new object[] {
                        Email,
                        Pass}, this.CrearUsuarioOperationCompleted, userState);
        }
        
        private void OnCrearUsuarioOperationCompleted(object arg) {
            if ((this.CrearUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearUsuarioCompleted(this, new CrearUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Login(string cuenta, string Pass) {
            object[] results = this.Invoke("Login", new object[] {
                        cuenta,
                        Pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string cuenta, string Pass) {
            this.LoginAsync(cuenta, Pass, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string cuenta, string Pass, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        cuenta,
                        Pass}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultadoSW {
        
        private string mensajeField;
        
        private bool respuestaField;
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public bool respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarParadaCompletedEventHandler(object sender, AgregarParadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarParadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarParadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BuscarParadaCompletedEventHandler(object sender, BuscarParadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarParadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarParadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarSugerenciaCompletedEventHandler(object sender, AgregarSugerenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarSugerenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarSugerenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarBusParadasCompletedEventHandler(object sender, AgregarBusParadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarBusParadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarBusParadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarBusCompletedEventHandler(object sender, AgregarBusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarBusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarBusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CambiarClaveCompletedEventHandler(object sender, CambiarClaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CambiarClaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CambiarClaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CrearUsuarioCompletedEventHandler(object sender, CrearUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoSW Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoSW)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591